### ISSUE TITLE
Manglende mulighed for at vælge KITOS indstillinger i Jammerbugt

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#100]
**Beskriv fejlen**
I Jammerbugt er der ikke importeret systemejer og systemansvarlige på aktiver. Jeg mistænker at det er fordi det ikke er blevet sat op under indstillinger. Men når jeg klikker på KITOS under indstillinger kommer mulighederne for at vælge hvor der skal importeres fra ikke frem - der kommer et blankt felt frem.

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk  hvad svarer til hvad så sætter jeg det lige op, og så kigger jeg bagefter på hvorfor du kan vælge det
