### ISSUE TITLE
Fejl ved oprettelse af et tilsyn (Ishøj)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#106]
**Beskriv fejlen**
Man kan ikke oprette tilsyn i OS2Compliance via leverandøren. 

Fejlen skyldes formentlig, at man ikke kan vælge et aktiv i formularen. Hvis man udfylder formularen og klikker gem (uden at have valgt et aktiv, fordi man ikke kan), så kommer fejlsiden med Whitelabel Error Page.

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk tilsyn "bor" på aktiverne, så derfor kan man ikke oprette et uden et aktiv.
Er der en use case for at lave tilsyn uden at leverandøren har et aktiv?

**Comment by nibisdk** [comment]
Ahhh, så gik sammenhæng op for mig. Det tilfælde vi oplevede var ift. tilsyn af OS2faktor på Digital Identity. Men hvis man ser i KITOS er det OS2 der står som leverandør på OS2faktor, så der er reelt ikke nogen tilknytning mellem Digital Identity og OS2faktor. Det er derfor balladen opstår. Reglen om at tilsyn "bor" på aktivet, giver rigtig fin mening, så lad os lade det forblive sådan for nu, og så vender jeg det med koordinationsgruppen :-)
