### ISSUE TITLE
Fejl i risikovurderingsmodulet hos Lolland 

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#108]
**Beskriv fejlen**
Se mail

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk jeg har ikke mulighed for at se noget i loggen eller genskabe, jeg har en mistanke om nettet måske har manglet?
Jeg har tilføjet fejlbeskeder som kommer løbende fremover hvis der sker fejl når den prøver at gemme, det skulle forhåbentlig modvirke at man kan sidde i lang tid uden at være klar over der er et problem.
