### ISSUE TITLE
Udvidelse af beskrivelsesfeltet for en opgave

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#109]
**Beskriv fejlen**
Man får fejl, hvis man indsætter mere end 253 i beskrivelsesfeltet for en opgave. Kan feltet udvides så man kan skrive mere tekst?

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk  det kan den fint, vi tager den med i 1.1
