### ISSUE TITLE
Stavefejl i risikovurderingerne

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#111]
**Beskriv fejlen**
I bunden af en risikovurdering står der "Tilknytede opgaver" vil du rette det til "Tilknyttede opgaver" (altså med 2 t´er)

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
Rettet i 1.1
