### ISSUE TITLE
Hos Syddjurs får man en fejl når man under dokumenter forsøger at knytte en ansvarlig, relationer eller tag

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#114]
**Beskriv fejlen**
Der kommer en boks frem hvor der står "fejl TypeError: Failed ti fetch"

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk  jeg kan ikke genskabe det, så jeg vi skal have sat et teams møde op hvor jeg kan se det er jeg bange for
