### ISSUE TITLE
Valg af risikovurderingsmatrix virker ikke i Syddjurs

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#115]
**Beskriv fejlen**
Hvis man klikker på tandhjulet og derefter risiko kommer der et blankt felt frem - jeg kan ikke få lov til at vælge model.

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk prøv lige at få dem til at prøve igen, der manglede en default setting, man kna kun vælge mellem 1-4 og 1-10 lige nu så ved ikke hvor meget værdi den giver... men kan godt tilføje flere hvis der skulle være brug for det.
