### ISSUE TITLE
Send til "system ejer" skal være et ord (I risikovurderingen)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#117]
**Beskriv fejlen**

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
Rettet i 1.1
