### ISSUE TITLE
Fejl i dashboard - viser ikke alle kontroller (Ishøj)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#118]
**Beskriv fejlen**
Jeg har sendt et skærmdump af Lars´ dashboard, hvor der mangler nogle kontroller

I opgaveoverblikket har Lars 20 opgaver listet, hvoraf jeg tænker de 13 bør fremgå af dashboardet - men der fremgår kun 7 opgaver. Umiddelbart tror jeg det er kommende kontroller der tidligere har været gennemført og derfor har en status der mangler.

Du får mail med skærmdump.

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk det er lige præcis kontroller som tidligere er gennemført der ikke fremgår.
Jeg har rettet fejlen, rettelsen kommer sammen med 1.1
