### ISSUE TITLE
Fejl i procen gennemført i ISO27002-2022 (Norddjurs)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#125]
Norddjurs oplyser, at ISO27002-2022 står som 100% gennemført til trods for at de har flere kontroller som er i status ”Ikke startet” og ”I gang”. Jeg har ikke adgang til deres løsning, og har derfor ikke kunne teste fejlen.

**Comment by kbp-di** [comment]
@nibisdk det fordi hovedelen står som fravalgt, det kun de tilvalgte der tæller med i regnskabet
