### ISSUE TITLE
Fejl i samspillet mellem dokument og opgave ift. beskrivelsen (Syddjurs)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#130]
**Beskriv fejlen**
Når man opretter et dokument og angiver en revideringsfrekvens så der dannes en opgave er det ikke beskrivelsen fra opgaven der kommer med i opgaven - burde det ikke være det?

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk det ved jeg ikke min tanke var det blot var en fast beskrivel "Revider X" - ved man godt hvad det drejer sig om hvis vi tager teksten fra documentet? - det kan jeg fint lave i hvert fald, selvom det kun vil virke fremadrettet.
