### ISSUE TITLE
Fejl i samspillet mellem dokument og opgave ift. dato (Syddjurs)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#131]
**Beskriv fejlen**
Retter man datoen i opgaven dannet ift. revidering af et dokument slår den nye dato igennem på dokumentet, men ændrer man datoen for revidering i dokumentet så slår den ikke igennem i opgaven. 

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk det virker omvendt, når jeg tester følger dokumentet ikke med hvis man retter deadline for opgave (det virker godt nok hvis man udfører den) - rettelse er på vej
