### ISSUE TITLE
Status farve på dokumenter og i dashboard (Syddjurs)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#132]
**Beskriv fejlen**
Farven på status under dokumenter og på dashboardet følger ikke farven på opgaven. Den er eksempelvis orange selvom der er mange måneder til opgaven skal udføres. Er det en fejl eller et udviklingsønske?

Princippet for farven ift. dokumenter og på dashboardet skal være den samme som ved opgaverne

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk men farven kommer jo fra dokumentets status, det har det jo hele tiden gjort, er det meningen at den i dashboarded skal følge en den tilknyttede opgave hvis der er en?

**Comment by nibisdk** [comment]
@bachpedersen Det er mig der har lavet en fejlantagelse. Da vi ændrede princippet for status (Udviklingsønske 40 - >1 md til deadline skal status være grå / 30-0 dage til deadline skal status være gul / overskredet skal være rød) så tænkte jeg at den ville slå igennem som statusprincip alle steder. Jeg kan godt se det ikke er en fejl, jeg opretter den som udviklingsønske :-)
