### ISSUE TITLE
Manglende indlæsning af systemejer (Middelfart)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#142]
Systemejer angivet i KITOS bliver ikke læst ind, trods korrekt mapping. 
I KITOS anvendes rollen "Systemansvarlig" for Systemejer hvilket er opsat korrekt i OS2compliance, men data indlæses ikke.

**Comment by kbp-di** [comment]
@nibisdk jeg synes da godt nok der er systemejere, kan du finde et it-system som eksempel?

**Comment by nibisdk** [comment]
Jeg har misforstået problematikken der i virkeligheden er et udviklingsønske som allerede er oprettet. Beklager, men du må gerne lukke denne fejl.
