### ISSUE TITLE
Ikke muligt at nulstille konsekvens på behandlingsaktivitet

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#143]
Det er ikke muligt at nulstikke konsekvensen på en behandlingsaktivitet. Hvis først værdien er sat til 1, 2, 3 eller 4 så kan man ikke slette tallet og dermed fjerne farven

**Comment by kbp-di** [comment]
Den skulle gerne være rettet i seneste version (1.2 prerelease)
