### ISSUE TITLE
Fjernelse af standard (Middelfart)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#144]
Du må ved lejlighed meget gerne fjerne ISO 27001 - 2017 fra Middelfart :-)

**Comment by kbp-di** [comment]
det er 27002 -2017 der menes ikke? @nibisdk

**Comment by nibisdk** [comment]
Undskyld, jo det er ISO27002-2017 jeg mener 🙈

**Comment by kbp-di** [comment]
@nibisdk så skulle den være slettet :)
