### ISSUE TITLE
Aktiver sorteres ikke alfabetisk (Herning)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#150]
**Beskriv fejlen**
Fejl meldt ind af Herning, men kan se det gør sig gældende for alle. 
Er det muligt at ændre, så Aktiver sorteres A-Å?

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
Denne er rettet og lagt på
