### ISSUE TITLE
Hvis først man sætter en ansvarlig på en behandlingsaktivitet, så kan denne ikke slettes / sættes til blank igen (Herning)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#151]
**Beskriv fejlen**
Når man klikker rediger kan man godt fjerne Ansvarlige forvaltninger, Ansvarlige afdelinger og Behandlingsansvarlige, men når man klikker gem så er de tilbage igen.

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
Denne er rettet og lagt på :)
