### ISSUE TITLE
Når man redigerer Formål & hjemmel under en behandling, så låses nederste Note felt ikke op (Herning)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#152]
**Beskriv fejlen**
Notefeltet kan ikke gøres tilgængelig for at skrive i. Virker heller ikke i Demo eller de andre kommuner

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
Denne skulle gerne være rettet i seneste version
