### ISSUE TITLE
Fjernelse af behandlingsansvarlig (Syddjurs)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#155]
**Beskriv fejlen**
Jeg har ved en test i Syddjurs-miljøet fået sat mig selv på som behandlingsansvarlig for behandlingsaktivitet "BL: 15. Behandling af personoplysninger i forbindelse med undervisning af tosprogede elever", og kan nu ikke slette mig. Vil I gøre det for mig?

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
Rettet og lagt på :)
