### ISSUE TITLE
Bug:  Security reporting email i still templated

### ISSUE THREAD

**Issue by janhalen** [OS2compliance/OS2compliance#163]
Correct email adress in SECURITY.md which is still in its template form: [insert-mail@os2.eu](mailto:insert-mail@os2.eu)

**Comment by kbp-di** [comment]
Which mail would be best to use, just os2@os2.eu?

**Comment by janhalen** [comment]
Historically our projects have used {projectname}@os2.eu, so if you wish to go this route i recommend contacting rasmus@os2.eu to make sure os2compliance@os2.eu exists and is redirecting to the right place. Alternatively (or as a supplement), we could experiment with enabling the GitHub built in feature for privately reporting security vulnerabilities?

Docs for the feature here: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability

Let me know what you think?

**Comment by kbp-di** [comment]
@janhalen I don't think it will be used often (hopefully never) and having an email and a manual process is imo. preferred.
I will contact Rasmus and check if the os2compliance mail i working :+1:

**Comment by janhalen** [comment]
@kbp-di : I fully understand your reasoning, and as a bonus we also avoid latching onto a GitHub specific feature if the project ever needs to move to another git hosting provider.
Great choice!

**Comment by kbp-di** [comment]
LOL - I should really have checked the actual file, now I se you fixed this a while back - wouldnt be suprised if i even merged it myself
