### ISSUE TITLE
Oprettelse af en ny systemtype under aktiver der hedder ”Ydelse”

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#165]
**Beskriv fejlen**
En letforståelig beskrivelse af fejlen

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
Denne er lavet og lagt  på demo, bliver rullet ud til kommunerne over de næste dage.
