### ISSUE TITLE
Dev og Demo virker ikke

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#166]
**Beskriv fejlen**
Jeg får følgende fejlbesked: 503 Service Temporarily Unavailable

Kommunerne virker, så det er kun Dev og Demo

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk ahh det var her den gemte sig, jeg kunne ikke finde mailen i går da jeg havde fikset det. Begge miljøer skulle virke igen :)
