### ISSUE TITLE
Fejl i risikovurderingen (Jammerbugt)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#167]
**Beskriv fejlen**
Jeg har den 30/7 oprettet en risikovurdering i Jammerbugt-miljøet for 1. Behandling af personoplysninger i forbindelse med ydelser vedr. jobafklaring, jobsøgning og uddannelsesforløb for ledige (Jeg står som risikoejer). Udfordringen er, at den behandlingsaktivitet slet ikke findes i fortegnelsen.
Generelt kan jeg ved risikovurdering af behandlingsaktiviteter søge behandlingsaktiviteter frem, som ikke er i fortegnelsen.

Hvis jeg kigger i fortegnelsen på hvor mange risikovurderinger der er gennemført er der 11 grønne og 21 gule. Kigger jeg i risikovurderingsmodulet er der 14 grønne og 24 gule. Der er dermed 6 gennemførte risikovurderinger der ikke er knyttet til en behandlingsaktivitet.

Dermed er der 2 fejl i denne som skal løses:

1. Vi skal finde ud af hvorfor der kan fremsøges behandlingsaktiviteter i risikovurderingsmodulet som ikke er i fortegnelsen
2. Vi skal finde ud af hvilke 6 gennemførte risikovurderinger der ikke er knyttet til en behandlingsaktivitet og få dem knyttet

(Note til mig selv: Når fejlen er rettet skal jeg slette den risikovurdering jeg har oprettet som test)

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
@nibisdk jeg kan finde nogen risikovurderinger af typen Behandlingsaktivitet som ikke har en tilknyttet behandlings aktivitet, tilgengæld kan jeg se at 4 af dem peger på slettede behandlingsaktiviteter (de er soft deleted, så de findes stadig )

**Comment by kbp-di** [comment]
@nibisdk nå problemet er at man kan oprette risikovurdering for slettede behandlignsaktiviteter, det er jeg ved at rette.
De 4 der ligger ser ud til de peger på nogle gamle inden de blev omdøbt, så dem tænker jeg at pege over på de rigtige så det gerne skulle komme til at stemme.

**Comment by kbp-di** [comment]
rettelse lagt på, i første omgang i jammerbugt - men de andre vil også blive opdateret i løbet af de næste dage.
