### ISSUE TITLE
Tilknytning til slettet IT-system fjernes ikke automatisk på leverandøren når it-systemet slettes (Ishøj)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#168]
**Beskriv fejlen**
Jeg har i Ishøj oprettet et it-system jeg kaldte "Test" og som jeg knyttede til leverandøren ABB A/S. Jeg har slettet systemet, men under leverandøren står det stadig tilknyttet. Klikker jeg på systemet via leverandøren får jeg en fejlside.

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
Denne er rettet vil blive lagt på kommunerne over de næste dage.
