### ISSUE TITLE
Fejl rækkefølge i NSIS tag rapport

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#178]
**Beskriv fejlen**
De gennemførte kontroller kommer ikke i datorækkefølge - se vedhæftede

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**
[OS2compliance - NSIS tag rapport.pdf](https://github.com/user-attachments/files/16743360/OS2compliance.-.NSIS.tag.rapport.pdf)

**Comment by kbp-di** [comment]
Rettet kun på dev indtil videre
