### ISSUE TITLE
Når man krydser af i send mail til ansvarlig modtages der ikke en mail (Ishøj)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#45]

**Comment by kbp-di** [comment]
@nibisdk synes det virker, den kommer 10dage før deadline - har du et eksempel hvor det ikke er sket?

**Comment by nibisdk** [comment]
Dem her i Ishøj har jeg aldrig fået en mail om. Sender den mail hvis opgaven oprettes med under 10 dage til udførelse?


***@***.***


Med venlig hilsen

Nina Birthe Sørensen

[Et billede, der indeholder tekst, clipart  Automatisk genereret beskrivelse]
[Et billede, der indeholder tekst  Automatisk genereret beskrivelse]


www.nibis.dk<http://www.nibis.dk/>
Tlf: 5180 4425
CVR: 43439537


Fra: kbp-di ***@***.***>
Sendt: 11. december 2023 12:10
Til: OS2compliance/OS2compliance ***@***.***>
Cc: Nina Birthe Sørensen ***@***.***>; Mention ***@***.***>
Emne: Re: [OS2compliance/OS2compliance] Når man krydser af i send mail til ansvarlig modtages der ikke en mail (Ishøj) (Issue #45)


@nibisdk<https://github.com/nibisdk> synes det virker, den kommer 10dage før deadline - har du et eksempel hvor det ikke er sket?

**Comment by nibisdk** [comment]
@kbp-di nu har jeg testet i dev og har desværre ikke modtaget mails, hverken hvis jeg har oprettet opgaven med deadline indenfor de næste 10 dage og efter 10 dage. (Jeg har tjekket spamfilter, og der er de ikke). Jeg har tidligere modtaget mails
