### ISSUE TITLE
Fortegnelse og fanen "Databehandling" - Databehandling for aktivet vises ikke

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#55]
Der bør være en bjælke for hver aktiv der er knyttet til behandlingsaktiviteten (Har virket tidligere)

**Comment by kbp-di** [comment]
Er rettet har du eksempel hvor det ikke virker på dev?

**Comment by nibisdk** [comment]
Den virker både i dev og hos kommunerne :-)
