### ISSUE TITLE
Aktiver: Forkert leverandør tilknyttet (Ishøj)

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#56]
Der kobles forkert leverandør til aktiver (Se MailChimp / The Rocket Science Group (USA)). Se mailkorrespondance

**Comment by kbp-di** [comment]
@nibisdk  den her er rettet men det er nødvendigt at manuelt ændre de 11 eller hvor mange det var det er forkert på, da rettelsen kun virker fremadrettet
