### ISSUE TITLE
(Fortegnelse/Formål & lovhjemmel) Over §8 skal der står "Databeskyttelsesloven"

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#71]
**Beskriv fejlen**
En letforståelig beskrivelse af fejlen

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by kbp-di** [comment]
som overskrift? eller hvordan
