### ISSUE TITLE
Ændringer i KITOS slår ikke igennem i OS2compliance

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#75]
Ishøj har fredag aften ændret systemejer for eksempelvis KMD Structura Miljø, men ændringen slår ikke igennem i OS2compliance.

**Comment by kbp-di** [comment]
Er den nye system ejer oprettet med samme email i kitos, og er system ejer rollen sat rigtig i OS2compliance indstillinger

**Comment by nibisdk** [comment]
Jeg kan ikke se hvilken mail hun er oprettet med i OS2compliance. I KITOS er hun oprettet med hendes Ishøjmail, og jeg antager at det også er den der kommer med via AD?

Når man klikker gem ift. KITOS opsætning i OS2compliance, så kan man ikke se hvad der er valgt. Jeg har forsøgt at vælge på ny, så jeg er sikker på at det er korrekt. Derudover har jeg på KMD Structura Miljø tilføjet Gro som ansvarlig (der var ikke nogen tilføjet i forvejen) for at se om det virker.
Men når jeg klikker ind på systemet, så er det stadig Morten der står som systemejer og der er ikke en systemansvarlig.

Jeg kan lige vise dig det på vores møde i morgen

**Comment by kbp-di** [comment]
@nibisdk Kitos har svaret tilbage, at det er et problem i deres ende og at de vil kigge ind i det, i det nye år.
Min umiddelbare tanke er at lave et midlertidligt i OS2compliance så den laver en fuld synkronisering om natten, så vil der gå en dag, men ændringerne vil trods alt slå igennem.

**Comment by nibisdk** [comment]
@kbp-di hvis det er muligt må du meget gerne lave den workaround indtil KITOS får fikset fejlen.
