### ISSUE TITLE
Manglende opdatering af NSIS hos Gentofte og Jammerbugt

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#86]
Det er kun hos Ishøj at versionen af NSIS hvor kravene er fuldt nummeret, eksempelvis med 3.1.1.1. 
Jeg har ikke adgang til Norddjurs, og ved derfor ikke om det er den rette version hos dem. Den er OK hos Ishøj.

**Comment by kbp-di** [comment]
Det er fordi Ishøj var den eneste der er opdateret til den version det var rettet i - jeg har bragt de andre op på samme version.
