### ISSUE TITLE
Deadlinefarver er ikke konsekvent rød når datoen er overskredet

### ISSUE THREAD

**Issue by nibisdk** [OS2compliance/OS2compliance#88]
**Beskriv fejlen**
En letforståelig beskrivelse af fejlen

**Genskab fejlen**
Beskriv hvordan man kan genskabe fejlen

**Forventet opførsel**
En letforståelig beskrivelse af hvad opførsel der var forventet

**Screenshots**
Hvis det giver mening tilføj gerne et screenshot.

**Yderligere information**

**Comment by nibisdk** [comment]
Den er ikke releaset til Kommunerne

**Comment by kbp-di** [comment]
Det er rettet - se på dev. 
De her issues lukker selv når vi har lagt koden ind, men det er ikke nødvendigvis online samtidig.
